version: '2'
services:

    apache-dummy:
        image: httpd:2.4
        container_name: slowloris-apache-dummy
        build:
            dockerfile: ./docker/dev/apache-dummy/Dockerfile
            context: ../..
        ports:
            - 80:80
        volumes:
            - ../dev/apache/httpd-dummy.conf:/usr/local/apache2/conf/httpd-dummy.conf
        networks:
            default:
                aliases:
                    - victim.localhost

    apache-protected:
        container_name: slowloris-apache-protected
        build:
            context: ../..
            dockerfile: ./docker/dev/apache-protected/Dockerfile
        extends:
            service: apache-dummy
        volumes:
            - ../dev/apache/httpd-protected.conf:/usr/local/apache2/conf/httpd-protected.conf

    attacker:
        image: slowloris-attacker
        container_name: slowloris-attacker
        entrypoint: ./docker/dev/attacker/entrypoint.sh
        build:
            context: ../..
            dockerfile: ./docker/dev/attacker/Dockerfile
        restart: 'no'
        env_file: ./env.conf
        volumes:
            - ../../:/code
        networks:
            default:

networks:
    default:
        driver: bridge