debug = true
checkNewVersion = false
logLevel = "INFO"

InsecureSkipVerify = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
[entryPoints.http]
address = ":80"
# [entryPoints.http.redirect]
# entryPoint = "https"
[entryPoints.https]
address = ":443"
[retry]
attempts = 1

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.dev"
exposedbydefault = false
watch = true